apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-db
  template:
    metadata:
      labels:
        app: library-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: library_db
            - name: POSTGRES_USER
              value: library_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: db-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "library_user", "-d", "library_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: library-db-pvc
